# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            CP tutorial
description:      'An introductive tutorial to Conformal Prediction.'
url:              https://conformalpredictionintro.github.io
baseurl:          /

author:
  name:           'Margaux Zaffran'
  url:            https://mzaffran.github.io/

paginate:         5

github:
  repo:           https://github.com/conformalpredictionintro/conformalpredictionintro.github.io
