# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            CP tutorial
tagline:          'A(nother) CP tutorial'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://conformalpredictionintro.github.io
baseurl:          /

author:
  name:           'Margaux Zaffran'
  url:            https://mzaffran.github.io/

paginate:         5

github:
  repo:           https://github.com/conformalpredictionintro/conformalpredictionintro.github.io
